
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author praja
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "First Name", "Last Name", "Gender", "Phone no", "Email Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 880, 140));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Home Service ID", "Name", "Type", "Charge", "Contact Person", "Phone no", "Email ID", "Address", "Area", "City", "State", "Pincode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 880, 140));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Salon ID", "Name", "Type", "Contact Person", "Phone no", "Email ID", "Address", "Area", "City", "State", "Pincode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 880, 140));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Home Service Information");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("User Information");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Salon Information");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Show");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Show");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Enter Home Service ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 120, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 51, 102));
        jButton4.setText("Delete Home Service");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Enter User ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 120, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 51, 102));
        jButton5.setText("Delete User");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Enter Salon ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 120, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 51, 102));
        jButton6.setText("Delete Salon");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 51));
        jButton7.setText("Log Out");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Samir\\project\\Hotel_Salon\\Project1\\img\\admin_background.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1153, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection connection = null;
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String username = "root";
            String pass = "mysql";
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_dbms", username,
            pass);
//            stmt = connection.createStatement();
        }
        catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            System.out.println("Error!!!");
        }
        
        try {
        Statement stat = connection.createStatement();
        String sqlp = "select user_id,user_First_name,user_Last_name,user_gender,user_phone_no_1,user_email_address from User_info";
        ResultSet rs = stat.executeQuery(sqlp);
        DefaultTableModel mod= (DefaultTableModel) jTable1.getModel();
        mod.setRowCount(0);
        while(rs.next()){
        ArrayList<String> data = new ArrayList<String>();
        data.add(rs.getString("user_id"));
        data.add(rs.getString("user_First_name"));
        data.add(rs.getString("user_Last_name"));
        String hh=rs.getString("user_gender");
        if(hh.equals("m") || hh.equals("M"))
        {
            data.add("Male");
        }
        else if(hh.equals("F") || hh.equals("f"))
        {
            data.add("Female");
        }
        data.add(rs.getString("user_phone_no_1"));
        data.add(rs.getString("user_email_address"));
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(data.toArray());
            }} catch (SQLException err) {
        System.out.println(err.getMessage());}   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Connection connection = null;
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String username = "root";
            String pass = "mysql";
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_dbms", username,
            pass);
//            stmt = connection.createStatement();
        }
        catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            System.out.println("Error!!!");
        }
        
        try {
        Statement stat = connection.createStatement();
        String sqlp = "select S_id,S_name,S_type,S_contanct_person,S_phone_no_1,S_email_address,S_address,"
                + "S_area,S_city,S_state,S_pincode from Salon_info";
        ResultSet rs = stat.executeQuery(sqlp);
        DefaultTableModel mod= (DefaultTableModel) jTable3.getModel();
        mod.setRowCount(0);
        while(rs.next()){
        ArrayList<String> data = new ArrayList<String>();
        data.add(rs.getString("S_id"));
        data.add(rs.getString("S_name"));
        String hh=rs.getString("S_type");
        if(hh.equals("b"))
        {
            data.add("Unisex");
        }
        else if(hh.equals("m"))
        {
            data.add("Only for Men");
        }
        else if(hh.equals("w"))
        {
            data.add("Only for Women");
        }
        data.add(rs.getString("S_contanct_person"));
        data.add(rs.getString("S_phone_no_1"));
        data.add(rs.getString("S_email_address"));
        data.add(rs.getString("S_address"));
        data.add(rs.getString("S_area"));
        data.add(rs.getString("S_city"));
        data.add(rs.getString("S_state"));
        data.add(rs.getString("S_pincode"));
        DefaultTableModel model= (DefaultTableModel) jTable3.getModel();
        model.addRow(data.toArray());
            }} catch (SQLException err) {
        System.out.println(err.getMessage());}   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection connection = null;
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String username = "root";
            String pass = "mysql";
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_dbms", username,
            pass);
//            stmt = connection.createStatement();
        }
        catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            System.out.println("Error!!!");
        }
        
        try {
        Statement stat = connection.createStatement();
        String sqlp = "select d.HS_id,d.HS_name,f.HS_type,f.HS_visiting_charge,d.HS_contanct_person,d.HS_phone_no_1,d.HS_email_address,d.HS_address,"
                + "d.HS_area,d.HS_city,d.HS_state,d.HS_pincode from Home_services_info as d natural join HS_visting_charge_entry as f";
        ResultSet rs = stat.executeQuery(sqlp);
        DefaultTableModel mod= (DefaultTableModel) jTable2.getModel();
        mod.setRowCount(0);
        while(rs.next()){
        ArrayList<String> data = new ArrayList<String>();
        data.add(rs.getString("d.HS_id"));
        data.add(rs.getString("d.HS_name"));
        String hh=rs.getString("f.HS_type");
        if(hh.equals("p"))
        {
            data.add("Plumber");
        }
        else if(hh.equals("c"))
        {
            data.add("Carpenter");
        }
        else if(hh.equals("e"))
        {
            data.add("Electrician");
        }
        data.add(rs.getString("f.HS_visiting_charge"));
        data.add(rs.getString("d.HS_contanct_person"));
        data.add(rs.getString("d.HS_phone_no_1"));
        data.add(rs.getString("d.HS_email_address"));
        data.add(rs.getString("d.HS_address"));
        data.add(rs.getString("d.HS_area"));
        data.add(rs.getString("d.HS_city"));
        data.add(rs.getString("d.HS_state"));
        data.add(rs.getString("d.HS_pincode"));
        DefaultTableModel model= (DefaultTableModel) jTable2.getModel();
        model.addRow(data.toArray());
            }} catch (SQLException err) {
        System.out.println(err.getMessage());}   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jTextField2.getText().isBlank())
        {
            JOptionPane.showMessageDialog(null,"Enter User ID");
        }
        else{
        String id_to_delete=jTextField2.getText();
        Connection connection = null;
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String username = "root";
            String pass = "mysql";
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_dbms", username,
            pass);
//            stmt = connection.createStatement();
        }
        catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            System.out.println("Error!!!");
        }
        
        try {
        Statement stat = connection.createStatement();
        String sqlp = "Select HS_Booking_id from HS_customer_address where Username_customer='"+id_to_delete+"'";
        ResultSet rs = stat.executeQuery(sqlp);
        while(rs.next()){
        String pwds = rs.getString("HS_Booking_id");
        try {
        Statement stats = connection.createStatement();
        String sqlps = "delete from Home_service_type_booking_info where HS_Booking_id='"+pwds+"'";
        stats.executeUpdate(sqlps);
        } catch (SQLException err) {
        System.out.println(err.getMessage());}
        }} catch (SQLException err) {
        System.out.println(err.getMessage());}
     
        
        try {
        Statement stat = connection.createStatement();
        String sqlp = "delete from HS_customer_address where Username_customer='"+id_to_delete+"'";
        stat.executeUpdate(sqlp);
        } catch (SQLException err) {
        System.out.println(err.getMessage());}
        
        try {
        Statement stat = connection.createStatement();
        String sqlp = "delete from Salon_booking_info where Username_customer='"+id_to_delete+"'";
        stat.executeUpdate(sqlp);
        } catch (SQLException err) {
        System.out.println(err.getMessage());}
               
        try {
        Statement stat = connection.createStatement();
        String sqlp = "delete from User_info where user_id='"+id_to_delete+"'";
        stat.executeUpdate(sqlp);
        } catch (SQLException err) {
        System.out.println(err.getMessage());}
        
        try {
        Statement stat = connection.createStatement();
        String sqlp = "delete from Username_pwd where Username='"+id_to_delete+"'";
        stat.executeUpdate(sqlp);
        } catch (SQLException err) {
        System.out.println(err.getMessage());}
        
        JOptionPane.showMessageDialog(null,"User removed Successfully");}
        jTextField2.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(jTextField3.getText().isBlank())
        {
            JOptionPane.showMessageDialog(null,"Enter Salon ID");
        }
        else{
        String id_to_delete=jTextField3.getText();
        Connection connection = null;
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String username = "root";
            String pass = "mysql";
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_dbms", username,
            pass);
//            stmt = connection.createStatement();
        }
        catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            System.out.println("Error!!!");
        }
        
        try {
        Statement stat = connection.createStatement();
        String sqlp = "delete from Salon_booking_info where S_id='"+id_to_delete+"'";
        stat.executeUpdate(sqlp);
        } catch (SQLException err) {
        System.out.println(err.getMessage());}
        
        try {
        Statement stat = connection.createStatement();
        String sqlp = "delete from Salon_info where S_id='"+id_to_delete+"'";
        stat.executeUpdate(sqlp);
        } catch (SQLException err) {
        System.out.println(err.getMessage());}
        
        try {
        Statement stat = connection.createStatement();
        String sqlp = "delete from organization_id_pwd where org_id='"+id_to_delete+"'";
        stat.executeUpdate(sqlp);
        } catch (SQLException err) {
        System.out.println(err.getMessage());}
        
        JOptionPane.showMessageDialog(null,"Salon removed Successfully");}
        jTextField3.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().isBlank())
        {
            JOptionPane.showMessageDialog(null,"Enter User ID");
        }
        else{
        String id_to_delete=jTextField1.getText();
        Connection connection = null;
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String username = "root";
            String pass = "mysql";
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_dbms", username,
            pass);
//            stmt = connection.createStatement();
        }
        catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            System.out.println("Error!!!");
        }
        
        try {
        Statement stat = connection.createStatement();
        String sqlp = "Select HS_Booking_id from HS_customer_address where HS_id='"+id_to_delete+"'";
        ResultSet rs = stat.executeQuery(sqlp);
        while(rs.next()){
        String pwds = rs.getString("HS_Booking_id");
        try {
        Statement stats = connection.createStatement();
        String sqlps = "delete from Home_service_type_booking_info where HS_Booking_id='"+pwds+"'";
        stats.executeUpdate(sqlps);
        } catch (SQLException err) {
        System.out.println(err.getMessage());}
        }} catch (SQLException err) {
        System.out.println(err.getMessage());}
     
        
        try {
        Statement stat = connection.createStatement();
        String sqlp = "delete from HS_customer_address where HS_id='"+id_to_delete+"'";
        stat.executeUpdate(sqlp);
        } catch (SQLException err) {
        System.out.println(err.getMessage());}
        
        try {
        Statement stat = connection.createStatement();
        String sqlp = "delete from HS_visting_charge_entry where HS_id='"+id_to_delete+"'";
        stat.executeUpdate(sqlp);
        } catch (SQLException err) {
        System.out.println(err.getMessage());}
               
        try {
        Statement stat = connection.createStatement();
        String sqlp = "delete from Home_services_info where HS_id='"+id_to_delete+"'";
        stat.executeUpdate(sqlp);
        } catch (SQLException err) {
        System.out.println(err.getMessage());}
        
        try {
        Statement stat = connection.createStatement();
        String sqlp = "delete from organization_id_pwd where org_id='"+id_to_delete+"'";
        stat.executeUpdate(sqlp);
        } catch (SQLException err) {
        System.out.println(err.getMessage());}
        
        JOptionPane.showMessageDialog(null,"Home Service removed Successfully");}
        jTextField1.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dispose();
        String a[] = new String[1];
        LoginJFrame.main(a);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
