
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author praja
 */
public class Salon_page extends javax.swing.JFrame {
    //public ArrayList<String> id = new ArrayList<String>(); 
//    public static String id_user;
    /**
     * Creates new form Salon_page
     */
    public Salon_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Salon Booking");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 260, 50));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--Select One--]" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 210, 30));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--Select One--]" }));
        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });
        jComboBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox5MouseClicked(evt);
            }
        });
        jPanel1.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 210, 30));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--Select One--]", "9AM - 10AM", "10AM - 11AM", "11AM - 12PM", "12PM - 1PM", "1PM - 2PM", "4PM - 5PM", "5PM - 6PM", "6PM - 7PM", "7PM - 8PM", "8PM - 9PM", " " }));
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 210, 30));

        jDateChooser1.setMinSelectableDate(new Date());
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 210, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter State :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 160, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address       :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 160, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Salon Type  :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 160, 50));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--Select One--]" }));
        jPanel1.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 210, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Preferred Date :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 200, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Preferred Time :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 200, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 80, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Enter City   :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 160, 50));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--Select One--]", "Unisex", "Only for Men", "Only for Women" }));
        jComboBox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox6ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 210, 30));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--Select One--]", " " }));
        jComboBox7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox7ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 210, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Available     :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 160, 50));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--Select One--]" }));
        jComboBox8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox8ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 210, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Book Appointment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 170, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter Area :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Samir\\project\\Hotel_Salon\\Project1\\img\\salon.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String[] a = {LoginJFrame.id_user};
        System.out.println(a[0]);
        dispose();
        user_mainpage.main(a);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        if(jComboBox5.getSelectedItem()=="[--Select One--]"){
            JOptionPane.showMessageDialog(null,"State Field can't remain empty");
        }
        else if(jComboBox8.getSelectedItem()=="[--Select One--]"){
            JOptionPane.showMessageDialog(null,"City Field can't remain empty");
        }
        else if(jComboBox7.getSelectedItem()=="[--Select One--]"){
            JOptionPane.showMessageDialog(null,"Area Field can't remain empty");
        }
        else if(jComboBox6.getSelectedItem()=="[--Select One--]"){
            JOptionPane.showMessageDialog(null,"Salon Type Field can't remain empty");
        }
        else if(jComboBox2.getSelectedItem()=="[--Select One--]"){
            JOptionPane.showMessageDialog(null,"Available Field can't remain empty");
        }
        else if(jComboBox9.getSelectedItem()=="[--Select One--]"){
            JOptionPane.showMessageDialog(null,"Address Field can't remain empty");
        }
        else if(DateFormat.getDateInstance().format(jDateChooser1.getDate()).isBlank()){
            JOptionPane.showMessageDialog(null,"Preferred Date Field can't remain empty");
        }
        else if(jComboBox4.getSelectedItem()=="[--Select One--]"){
            JOptionPane.showMessageDialog(null,"Preferred Time can't remain empty");
        }
        else{
            String data[] = {LoginJFrame.id_user,String.valueOf(jComboBox5.getSelectedItem()),String.valueOf(jComboBox8.getSelectedItem()),
                String.valueOf(jComboBox7.getSelectedItem()),String.valueOf(jComboBox6.getSelectedItem()),
                String.valueOf(jComboBox2.getSelectedItem()),String.valueOf(jComboBox9.getSelectedItem()),
                DateFormat.getDateInstance().format(jDateChooser1.getDate()),String.valueOf(jComboBox4.getSelectedItem())};
//            for(String s:data){
//                        System.out.println(s);
//            }
            if(data[4].equals("Unisex")){
            data[4]="b";
            }
            else if(data[4].equals("Only for Men"))
            {
                data[4]="m";
            }
            else if(data[4].equals("Only for Women"))
            {
                data[4]="w";
            }
            MysqlConnection.connected(7,data);
            
        }}catch(Exception e){
            JOptionPane.showMessageDialog(null,"Preferred Date Field Entry is not valid");}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox6ItemStateChanged
        // TODO add your handling code here:
        jComboBox2.setPreferredSize(new Dimension (229,28));
        jComboBox2.removeAllItems();
        jComboBox2.addItem("[--Select One--]");
        jComboBox9.setPreferredSize(new Dimension (229,28));
        jComboBox9.removeAllItems();
        jComboBox9.addItem("[--Select One--]");
        
        if(jComboBox7.getSelectedItem()!="[--Select One--]" && jComboBox8.getSelectedItem()!="[--Select One--]" && jComboBox5.getSelectedItem()!="[--Select One--]"
                && jComboBox6.getSelectedItem()!="[--Select One--]"){
            jComboBox2.setPreferredSize(new Dimension (229,28));
            jComboBox2.removeAllItems();
            jComboBox2.addItem("[--Select One--]");
            String data[] = {String.valueOf(jComboBox7.getSelectedItem()),String.valueOf(jComboBox8.getSelectedItem()),
            String.valueOf(jComboBox5.getSelectedItem()),String.valueOf(jComboBox6.getSelectedItem())};
            if(data[3].equals("Unisex")){
            data[3]="b";
            }
            else if(data[3].equals("Only for Men"))
            {
                data[3]="m";
            }
            else if(data[3].equals("Only for Women"))
            {
                data[3]="w";
            }
            Connection connection = null;
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String username = "root";
            String pass = "mysql";
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_dbms", username,
            pass);
//            stmt = connection.createStatement();
        }
        catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            System.out.println("Error!!!");
        }
        try {
        Statement stat = connection.createStatement();
        String sqlp = "Select S_name from salon_info where S_area='"+data[0]+"' and S_city='"+data[1]+"' and S_state='"+data[2]+"' and S_type='"+data[3]+"'";
        ResultSet rs = stat.executeQuery(sqlp);
        while(rs.next()){
        String pwds = rs.getString("S_name");
        //String ids = rs.getString("S_id");
        //id.add(ids);
        jComboBox2.addItem(pwds);
        }
        connection.close();
        stat.close();} catch (SQLException err) {
        System.out.println(err.getMessage());}
        }
        else{
            jComboBox2.removeAllItems();
            jComboBox2.addItem("[--Select One--]");
        }
        jComboBox2.setPreferredSize(new Dimension (229,28));
    }//GEN-LAST:event_jComboBox6ItemStateChanged

    private void jComboBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox5MouseClicked
        // TODO add your handling code here:
        jComboBox5.setPreferredSize(new Dimension (229,28));
        jComboBox5.removeAllItems();
        jComboBox5.addItem("[--Select One--]");    
        Connection connection = null;
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String username = "root";
            String pass = "mysql";
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_dbms", username,
            pass);
//            stmt = connection.createStatement();
}
        catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            System.out.println("Error!!!");
        }
        try {
        Statement stat = connection.createStatement();
        String sqlp = "Select distinct S_state from salon_info";
        ResultSet rs = stat.executeQuery(sqlp);
        while(rs.next()){
        String pwds = rs.getString("S_state");
        jComboBox5.addItem(pwds);
        }
        connection.close();
        stat.close();} catch (SQLException err) {
        System.out.println(err.getMessage());}
        jComboBox5.setPreferredSize(new Dimension (229,28));
    }//GEN-LAST:event_jComboBox5MouseClicked

    private void jComboBox8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox8ItemStateChanged
        // TODO add your handling code here:
        jComboBox7.setPreferredSize(new Dimension (229,28));
        jComboBox7.removeAllItems();
        jComboBox7.addItem("[--Select One--]");
        jComboBox2.setPreferredSize(new Dimension (229,28));
        jComboBox2.removeAllItems();
        jComboBox2.addItem("[--Select One--]");
        jComboBox9.setPreferredSize(new Dimension (229,28));
        jComboBox9.removeAllItems();
        jComboBox9.addItem("[--Select One--]");
        
        
        if(jComboBox5.getSelectedItem()!="[--Select One--]" && jComboBox8.getSelectedItem()!="[--Select One--]"){
            jComboBox7.setPreferredSize(new Dimension (229,28));
            jComboBox7.removeAllItems();
            jComboBox7.addItem("[--Select One--]");
            String data = String.valueOf(jComboBox5.getSelectedItem());
            String data1 = String.valueOf(jComboBox8.getSelectedItem());
            Connection connection = null;
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String username = "root";
            String pass = "mysql";
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_dbms", username,
            pass);
//            stmt = connection.createStatement();
        }
        catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            System.out.println("Error!!!");
        }
        try {
        Statement stat = connection.createStatement();
        String sqlp = "Select distinct S_area from salon_info where S_state='"+data+"' and S_city='"+data1+"'";
        ResultSet rs = stat.executeQuery(sqlp);
        while(rs.next()){
        String pwds = rs.getString("S_area");
        jComboBox7.addItem(pwds);
        }
        connection.close();
        stat.close();} catch (SQLException err) {
        System.out.println(err.getMessage());}
        }
        else{
            jComboBox7.removeAllItems();
            jComboBox7.addItem("[--Select One--]");
        }
        jComboBox7.setPreferredSize(new Dimension (229,28));
    }//GEN-LAST:event_jComboBox8ItemStateChanged

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
        // TODO add your handling code here:
        jComboBox8.setPreferredSize(new Dimension (229,28));
        jComboBox8.removeAllItems();
        jComboBox8.addItem("[--Select One--]");
        jComboBox7.setPreferredSize(new Dimension (229,28));
        jComboBox7.removeAllItems();
        jComboBox7.addItem("[--Select One--]");
        jComboBox2.setPreferredSize(new Dimension (229,28));
        jComboBox2.removeAllItems();
        jComboBox2.addItem("[--Select One--]");
        jComboBox9.setPreferredSize(new Dimension (229,28));
        jComboBox9.removeAllItems();
        jComboBox9.addItem("[--Select One--]");
            
        if(jComboBox5.getSelectedItem()!="[--Select One--]"){
            jComboBox8.setPreferredSize(new Dimension (229,28));
            jComboBox8.removeAllItems();
            jComboBox8.addItem("[--Select One--]");
            String data[] = {String.valueOf(jComboBox5.getSelectedItem())};
            Connection connection = null;
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String username = "root";
            String pass = "mysql";
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_dbms", username,
            pass);
//            stmt = connection.createStatement();
        }
        catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            System.out.println("Error!!!");
        }
        try {
        Statement stat = connection.createStatement();
        String sqlp = "Select distinct S_city from salon_info where S_state='"+data[0]+"'";
        ResultSet rs = stat.executeQuery(sqlp);
        while(rs.next()){
        String pwds = rs.getString("S_city");
        System.out.println(pwds);
        jComboBox8.addItem(pwds);
        }
        connection.close();
        stat.close();} catch (SQLException err) {
        System.out.println(err.getMessage());}
        }
        else{
            jComboBox8.removeAllItems();
            jComboBox8.addItem("[--Select One--]");
        }
        jComboBox8.setPreferredSize(new Dimension (229,28));
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void jComboBox7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox7ItemStateChanged
        // TODO add your handling code here:
        jComboBox6.setSelectedItem("[--Select One--]");
        jComboBox2.setPreferredSize(new Dimension (229,28));
        jComboBox2.removeAllItems();
        jComboBox2.addItem("[--Select One--]");
        jComboBox9.removeAllItems();
        jComboBox9.addItem("[--Select One--]");
        
    }//GEN-LAST:event_jComboBox7ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        jComboBox9.setPreferredSize(new Dimension (229,28));
        jComboBox9.removeAllItems();
        jComboBox9.addItem("[--Select One--]");
        
        if(jComboBox7.getSelectedItem()!="[--Select One--]" && jComboBox8.getSelectedItem()!="[--Select One--]" && jComboBox5.getSelectedItem()!="[--Select One--]"
                && jComboBox6.getSelectedItem()!="[--Select One--]" && jComboBox2.getSelectedItem()!="[--Select One--]"){
            jComboBox9.setPreferredSize(new Dimension (229,28));
            jComboBox9.removeAllItems();
            jComboBox9.addItem("[--Select One--]");
            String data[] = {String.valueOf(jComboBox7.getSelectedItem()),String.valueOf(jComboBox8.getSelectedItem()),
            String.valueOf(jComboBox5.getSelectedItem()),String.valueOf(jComboBox6.getSelectedItem()),String.valueOf(jComboBox2.getSelectedItem())};
            if(data[3].equals("Unisex")){
            data[3]="b";
            }
            else if(data[3].equals("Only for Men"))
            {
                data[3]="m";
            }
            else if(data[3].equals("Only for Women"))
            {
                data[3]="w";
            }
            Connection connection = null;
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String username = "root";
            String pass = "mysql";
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_dbms", username,
            pass);
//            stmt = connection.createStatement();
        }
        catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            System.out.println("Error!!!");
        }
        try {
        Statement stat = connection.createStatement();
        String sqlp = "Select S_address from salon_info where S_name='"+data[4]+"' and S_area='"+data[0]+"' and S_city='"+data[1]+"' and S_state='"+data[2]+"' and S_type='"+data[3]+"'";
        ResultSet rs = stat.executeQuery(sqlp);
        while(rs.next()){
        String pwds = rs.getString("S_address");
        jComboBox9.addItem(pwds);
        }
        connection.close();
        stat.close();} catch (SQLException err) {
        System.out.println(err.getMessage());}
        }
        else{
            jComboBox9.removeAllItems();
            jComboBox9.addItem("[--Select One--]");
        }
        jComboBox9.setPreferredSize(new Dimension (229,28));
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        LoginJFrame.id_user=args[0];
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salon_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salon_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salon_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salon_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salon_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
